# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doclang < Formula
  desc "DocLang compiler and AST toolkit"
  homepage "https://go.ziradocs.com"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.0.0/doclang_2.0.0_darwin_amd64.tar.gz"
      sha256 "935d13fa70718a7df4912f1309d793033c32c8ca306610a16cc453c2f3ead9c1"

      define_method(:install) do
        bin.install "doclang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.0.0/doclang_2.0.0_darwin_arm64.tar.gz"
      sha256 "fa0370f04033bfd2b6bad9ce52074d98cfbb01a145566c6c3637b8f9694cda32"

      define_method(:install) do
        bin.install "doclang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.0.0/doclang_2.0.0_linux_amd64.tar.gz"
      sha256 "7c1e492da5bcc42b06b7c0fdb8700f16ac7cecbafb49667327a0f21cc72b1ed3"
      define_method(:install) do
        bin.install "doclang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.0.0/doclang_2.0.0_linux_arm64.tar.gz"
      sha256 "ead535eae5f8da3bb627fd348e4d4187a8f6584a87fe4ffb28be24d6d683a4bf"
      define_method(:install) do
        bin.install "doclang"
      end
    end
  end
end
