# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doclang < Formula
  desc "DocLang compiler and AST toolkit"
  homepage "https://go.ziradocs.com"
  version "2.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.2.2/doclang_2.2.2_darwin_amd64.tar.gz"
      sha256 "4965d2c71a773cf6937a4cbd5b5acd8938bfc20aef024dad2dcc46d49b413e78"

      define_method(:install) do
        bin.install "doclang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.2.2/doclang_2.2.2_darwin_arm64.tar.gz"
      sha256 "48f6cecc868d91ddc1aa88d4b8881b8ffc18d082ea70dc09fe6c927391dd0419"

      define_method(:install) do
        bin.install "doclang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.2.2/doclang_2.2.2_linux_amd64.tar.gz"
      sha256 "621626dc9c36e8744ec8946545b331c8d678905609bdb0733ddf2dfce77908e3"
      define_method(:install) do
        bin.install "doclang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.2.2/doclang_2.2.2_linux_arm64.tar.gz"
      sha256 "52877f5b7fd9e23f6d6429f388abb90e5f4fc4facd9f30253b5f6347edc078de"
      define_method(:install) do
        bin.install "doclang"
      end
    end
  end
end
