# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slidelang < Formula
  desc "SlideLang compiler and AST toolkit"
  homepage "https://go.ziradocs.com"
  version "2.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.13.0/slidelang_2.13.0_darwin_amd64.tar.gz"
      sha256 "af2027b0f7ee9fb938721c751baf9a23cb0f163323a0186d99638683f8689c60"

      define_method(:install) do
        bin.install "slidelang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.13.0/slidelang_2.13.0_darwin_arm64.tar.gz"
      sha256 "5b1d86f438b3db49be332bb6096cac0ae603426d45652b08b22a8dadf9658a40"

      define_method(:install) do
        bin.install "slidelang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.13.0/slidelang_2.13.0_linux_amd64.tar.gz"
      sha256 "5019783fa88310865461c099679011458a48e3d142194f214cd4507f2af6dd5c"
      define_method(:install) do
        bin.install "slidelang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ziradocs/toolchain/releases/download/v2.13.0/slidelang_2.13.0_linux_arm64.tar.gz"
      sha256 "e2dda8e5521072a76c58316a4fe1ddd1f8139875a4c68e72f0ecc7563fdb0510"
      define_method(:install) do
        bin.install "slidelang"
      end
    end
  end
end
